version: '3.8'
services:
  iouone_db:
    build:
      context: ./iouone-db
    image: fallsoft/iouone_db:latest
    ports:
      - 3306:3306
    container_name: iouone_db
    environment:
      - MYSQL_ROOT_PASSWORD=IouOne@147
      - MYSQL_DATABASE=iouone_hml
      - MYSQL_USER=iouone
      - MYSQL_PASSWORD=iouone-db
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

  iouone-serv:
    build:
      context: ../iouone-serv
      dockerfile: ../iouone-serv/Dockerfile
      args:
        EXPOSE_PORT: 7074
    image: fallsoft/iouone-serv:latest
    ports:
      - 7074:7074
    container_name: iouone-serv
    environment:
      spring.profiles.active: hml
      SPRING_DATASOURCE_URL: jdbc:mysql://iouone_db:3306/iouone_hml
      SPRING_DATASOURCE_USERNAME: iouone
      SPRING_DATASOURCE_PASSWORD: iouone-db
    depends_on:
      - iouone_db
    networks:
      - backend
    restart: unless-stopped
networks:
  backend:
    driver: "bridge"