spring:
  application:
    name: mspayment
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/iouone_pagamento_hml?useTimezone=true&serverTimezone=UTC
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: ${PORT:7075}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

pagarme:
  api:
    username: sk_82717935ef0e406f89fc8ab52b094b47
    password: IouOne@147

mq:
  queue:
    pessoa_registration: pessoa_registration_queue
