spring:
  application:
    name: mspayment
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

pagarme:
  api:
    username: sk_test_6bebfceaf6da4006bc6299a419ee90e3
    password: IouOne@147

mq:
  queue:
    pessoa_registration: pessoa_registration_queue
