spring:
  application:
    name: mspayment
  rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:iouone}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://iouone_db:3306/iouone_pagamento_prd?useTimezone=true&serverTimezone=UTC}
    password: ${SPRING_DATASOURCE_PASSWORD:iouone-db}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: ${PORT:7072}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

pagarme:
  api:
    username: sk_82717935ef0e406f89fc8ab52b094b47
    password: IouOne@147

mq:
  queue:
    pessoa_registration: pessoa_registration_queue
